### ISSUE TITLE
Address Data needs Latitude and Longitude for Metabase (if we use Metabase)

### ISSUE THREAD

**Issue by DanLindeman** [dwelling-place/dwelling-place#13]
Turns out the Metabase Map display widget needs to have longitude and latitude. If we use Metabase, the data needs lat/long and a Google Maps API key. http://www.metabase.com/docs/v0.12.0/users-guide/04-visualizing-results

**Comment by jacebrowning** [comment]
We could potentially do an address lookup in Python when processing the input spreadsheets.

**Comment by AstraLuma** [comment]
Since it's displayed on a map, we can use the Google API to do the lookup and then cache the results against the address.
