### ISSUE TITLE
Evaluate Visualization Generators/Front End

### ISSUE THREAD

**Issue by brousch** [dwelling-place/dwelling-place#16]
Evaluate and discuss the following front ends:

- [Microsoft Power BI](https://powerbi.microsoft.com/en-us/)
- [Metabase](http://www.metabase.com/)
- [Plot.ly](https://plot.ly/)

**Comment by DanLindeman** [comment]
I'm looking into Metabase, @ramwho was still working with MS BI, @RachellCalhoun will look at Plot.ly
