### ISSUE TITLE
Cleanup: Yardi - Trial Balance

### ISSUE THREAD

**Issue by brondsem** [dwelling-place/dwelling-place#3]
Input is: Trial Balance excel file  (could be CSV I think if we want)

Output should match "DP Metrics" tab, columns Economic Vacancy and Tenant Receivables

**Comment by brondsem** [comment]
All "bierma" and "biermc" rows need to be combined into "bierma"

**Comment by AstraLuma** [comment]
Not being implemented: No consistent input for too little output.
