### ISSUE TITLE
Final heroku setup

### ISSUE THREAD

**Issue by brondsem** [dwelling-place/dwelling-place#32]
Deploy app to the main heroku instance, make sure Dwelling Place has login, etc.

**Comment by jacebrowning** [comment]
Here's what I'm thinking:
- [x] Set a different password for production (WSGI_AUTH_CREDENTIALS env var)
- [x] Clear out the data
- [x] Clear out data in BI
- [x] Upload real spreadsheets
- [x] Create `stable` branch for production deploys
- [x] password handoff
