### ISSUE TITLE
Set the width of columns, in xlsx export

### ISSUE THREAD

**Issue by brondsem** [dwelling-place/dwelling-place#33]
They default to being very narrow and you can't read the column names

**Comment by jacebrowning** [comment]
As @brousch suggested, we might be able to store the last width from upload.

**Comment by brousch** [comment]
I used a 1" column width as a reasonable default in the master blank template.

**Comment by brondsem** [comment]
http://xlsxwriter.readthedocs.io/worksheet.html?highlight=width#set_column for writing

https://groups.google.com/forum/#!topic/python-excel/ThhXGxxIVKw shows there are quite a few things we could check in xlrd for reading it.
