### ISSUE TITLE
bug: http auth prompt during upload

### ISSUE THREAD

**Issue by brondsem** [dwelling-place/dwelling-place#58]
:(

**Comment by brousch** [comment]
I'm not seeing this.

**Comment by jacebrowning** [comment]
# Steps
1. Go to https://dwelling-place-staging.herokuapp.com/
2. Select a file to upload
3. Click upload

## Expected

"successful upload" messages flashes.

## Actual

Password prompt.

**Comment by brondsem** [comment]
I don't get this locally, only on heroku

**Comment by brondsem** [comment]
This is because you auth on https once, and then the app ends up on http and you need to auth again.  Closing in favor of #66
